### ISSUE TITLE
Is there any code available?

### ISSUE THREAD

**Issue by Mythszj** [grenlayk/text-deep-fake#2]
I am really interested in this amazing work. And currently I am looking for a code implementation to study. 
Really looking forward to your code.🙂️

**Comment by grenlayk** [comment]
Hi Mythsz,
 
We are working hard on it! It is our university coursework and we plan to finish it till June.

**Comment by Mythszj** [comment]
> Hi Mythsz,
> 
> We are working hard on it! It is our university coursework and we plan to finish it till June.

Thanks for your reply! May I ask if you know any open source code related to this work?

**Comment by grenlayk** [comment]
> > Hi Mythsz,
> > We are working hard on it! It is our university coursework and we plan to finish it till June.
> 
> Thanks for your reply! May I ask if you know any open source code related to this work?

As much as we know, for now there is no open source code with architecture described in the [original paper](https://arxiv.org/pdf/2106.08385.pdf). This is why we want to implement it ourselves. However, you can check "Related Work" section, most of the resources there are open source.

**Comment by Mythszj** [comment]
> > Thanks for your reply! May I ask if you know any open source code related to this work?
> 
> As much as we know, for now there is no open source code with architecture described in the [original paper](https://arxiv.org/pdf/2106.08385.pdf). This is why we want to implement it ourselves. However, you can check "Related Work" section, most of the resources there are open source.

Thanks a lot!
