### ISSUE TITLE
No such file or directory: 'data/IMGUR5K/train/words.json' ?

### ISSUE THREAD

**Issue by kbaicai** [grenlayk/text-deep-fake#25]
This is an interesting work. but i got an error when I try to run the project by follow command
`python run.py './src/config/baseline.py' `
but I have download IMGUR5K dataset and put it under data floder. So waht should i do to generate training dataset from IMGUR5K?

**Comment by grenlayk** [comment]
Hi @kbaicai, we updated repo and added [prepare_dataset.py](https://github.com/grenlayk/text-deep-fake/blob/main/prepare_dataset.py) file. Run it to preprocess files as we did it. Also you can find updated instructions in readme.

**Comment by kbaicai** [comment]
it works! thank you~
but there are some bug need to fix in prepare_dataset.py
line 83
`img_cropped = crop_minAreaRect(img, *info['bounding_box'])
 change to 
`img_cropped = crop_minAreaRect(img, *json.loads(info['bounding_box']))

**Comment by Loganavter** [comment]
prepare_dataset.py not work
Traceback (most recent call last):
  File "/home/jorj/Загрузки/text-deep-fake-main/venv/lib/python3.7/site-packages/click/types.py", line 608, in convert
    st = os.stat(rv)
FileNotFoundError: [Errno 2] No such file or directory: 'dataset_info'
