### ISSUE TITLE
Google Colab raises errors due to Python3.7 version

### ISSUE THREAD

**Issue by grenlayk** [grenlayk/text-deep-fake#4]
We need script to easily update system if it does not match our requirements.

**Comment by SphericalPotatoInVacuum** [comment]
After some testing I think it would be better and easier to downgrade required python version to `3.7.13` as used by the colab, and update the requirements and the code accordingly. As soon as we have a way to do our training/experiments somewhere where we can fully control the environment we can bump the versions back up.
